version: "3"

services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
    restart: always
